# Generated by Django 4.2.8 on 2023-12-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_info',
            new_name='StockInfo',
        ),
    ]
